In [1]:
import numpy as np

In [26]:
# Array de 1 e 2 dimensões
one_dim = np.array([1,2,3,4])
two_dim = np.array([(1,2,3), (4,5,6)])
print(one_dim)
print(two_dim)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [4]:
# Cria um array de números aleatórios.
# Um array de 5 linhas e duas dimensões.
x = np.random.random((5,2))
print(x)

[[0.13501408 0.00478674]
 [0.40867934 0.68988681]
 [0.14655346 0.78237904]
 [0.54208505 0.0614782 ]
 [0.59528021 0.98225821]]


In [10]:
# Retorna a quantidade de dimensões.
print(two_dim.ndim)
# Imprimindo o valor máximo do array.
print(two_dim.max())
# Imprimindo o valor médio.
print(two_dim.mean())
# Imprimindo o desvio padrão.
print(two_dim.std())
# mostra a quantidade
print(two_dim.size)

2
6
3.5
1.707825127659933
6


In [20]:
tree = np.random.random((5,3))
print(tree)

[[0.30114802 0.46143327 0.61848131]
 [0.15208703 0.29638155 0.51855147]
 [0.68206435 0.90261488 0.0404644 ]
 [0.83276701 0.10272954 0.0182396 ]
 [0.18766511 0.78134058 0.12306935]]


In [21]:
# Transforma em uma matriz com 3 linhas e 5 colunas
tree.reshape(3,5)

array([[0.30114802, 0.46143327, 0.61848131, 0.15208703, 0.29638155],
       [0.51855147, 0.68206435, 0.90261488, 0.0404644 , 0.83276701],
       [0.10272954, 0.0182396 , 0.18766511, 0.78134058, 0.12306935]])

In [27]:
# Adicionando elementos a um array.
two_dim = np.insert(two_dim,0,7) #adiciona 7 na posicao 0
two_dim

array([7, 1, 2, 3, 4, 5, 6])

In [28]:
# Apagando o elemento da primeira posição do array.
two_dim = np.delete(two_dim,[0])
two_dim

array([1, 2, 3, 4, 5, 6])

In [32]:
my_array = np.random.random([10,2])
my_array

array([[0.03831613, 0.76182179],
       [0.40124224, 0.80549727],
       [0.95681863, 0.29435484],
       [0.15157621, 0.15360168],
       [0.54458908, 0.65217533],
       [0.16075212, 0.03935662],
       [0.94978684, 0.04487105],
       [0.80971448, 0.02119393],
       [0.75044573, 0.90495769],
       [0.49679683, 0.63745125]])

In [33]:
# Imprimindo o primeiro elemento da coluna 0 (1 coluna)
my_array[0][0]

0.03831613008974388

In [34]:
# Imprimindo até 3 valores da coluna 1
my_array[:3,1]

array([0.76182179, 0.80549727, 0.29435484])

In [35]:
# Imprime todas as linhas da coluna 2 * 10
my_array[:,1] * 10

array([7.61821785, 8.05497269, 2.94354836, 1.53601681, 6.52175331,
       0.39356622, 0.44871048, 0.21193935, 9.0495769 , 6.37451245])

In [36]:
# Acessando valores por índices
my_array[my_array > 0.50]

array([0.76182179, 0.80549727, 0.95681863, 0.54458908, 0.65217533,
       0.94978684, 0.80971448, 0.75044573, 0.90495769, 0.63745125])